### ISSUE TITLE
Application hangs at 'Computing Deck Suggestions...' after updating to v1.0.3.0

### ISSUE THREAD

**Issue by ghost** [jceddy/DailyArenaDeckAdvisor#18] opened 2019-09-06 00:45 UTC
Updated this evening and application hangs with 'Computing Deck Suggestions...' in the main window.

Running Windows 7 Home x64

**Comment by jceddy** [comment] 2019-09-06 01:14
You need to go to Settings->View Account and check "Detailed Logs(Plugin Support)" to get inventory data dumped to the logs now. Have you done that?

**Comment by ghost** [comment] 2019-09-06 01:21
That did it. Thanks!

**Comment by jceddy** [comment] 2019-09-06 01:22
I put 1.0.3.0 up a little early to fix a bug due to the new cards showing up in the card database with missing fields. I will make a post with information about the new Arena setting tomorrow.

Closing this for now.

**Closed as completed by jceddy** 2019-09-06 01:22 UTC

**Comment by Dhurcator** [comment] 2019-09-17 20:45
hi, i have the same problem and i have 1.0.3.2. and i did the Settings->View Account and check "Detailed Logs(Plugin Support)" but still hangs with 'Computing Deck Suggestions...' in the main window

**Comment by jceddy** [comment] 2019-09-18 01:04
Was it working for you before?

There is another troubleshooting item in the User Guide to check as well. Let me know if none of the workaround work for you!

https://github.com/jceddy/DailyArenaDeckAdvisor/wiki/User-Guide

**Comment by Dhurcator** [comment] 2019-09-18 12:52
hi,
it was working before the last 2 updates i think and unfortunately the
options on troubleshooting (inventory and video card) are there, i mean,
the inventory, the line is there as it should and in the video card, the
line is linear as said in the troubleshooting.

i'm sorry for annoying you with this but your program is a must have and
i'm kind lost without him! lol

thank you

jceddy <notifications@github.com> escreveu no dia quarta, 18/09/2019 à(s)
02:04:

**Comment by jceddy** [comment] 2019-09-18 13:07
I recently actually had this happen to me using the same version (1.0.3.2) recently after adding some information to the decks download ahead of an upcoming change for the next version.

Closing and re-opening the program fixed it for me, though, and I haven't had a chance yet to dig further into it. I just wanted to eliminate the possibility of it being one of the "known" issues before going deeper here.

If you could attach the latest log files from C:\Users\\{your user}\AppData\LocalLow\DailyArena\DailyArenaDeckAdvisor\logs here, I will take a look at them and see if it help narrow it down.

Will also spend some time today to see if I can reproduce it on my end (I was going to do that anyway, but will prioritize it since it's affecting other users).

**Comment by jceddy** [comment] 2019-09-18 13:16
Also, try deleting all of the json files in C:\Users\\{your user}\AppData\LocalLow\DailyArena\DailyArenaDeckAdvisor, and then re-running the program.

**Comment by jceddy** [comment] 2019-09-18 13:40
I found the exception I originally saw in my log file and will be investigating it...curious to see if it's the same error in your log:

    {"@t":"2019-09-16T18:33:18.2447319Z","@mt":"Exception in {0} ({1} - {2})","@l":"Error","@x":"System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.\r\nParameter name: key\r\n   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)\r\n   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)\r\n   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)\r\n   at DailyArenaDeckAdvisor.MainWindow.ReloadAndCrunchAllData()\r\n   at System.Threading.Tasks.Task.Execute()\r\n   --- End of inner exception stack trace ---\r\n---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.\r\nParameter name: key\r\n   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)\r\n   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)\r\n   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)\r\n   at DailyArenaDeckAdvisor.MainWindow.ReloadAndCrunchAllData()\r\n   at System.Threading.Tasks.Task.Execute()<---\r\n","0":"loadTask","1":"Window_Loaded","2":"Main Application"}

Also, no need to apologize for pursuing it...it's harder for me to track down bugs if people don't complain about them! :)

**Comment by jceddy** [comment] 2019-09-18 13:48
Let me know if deleting the JSON files works...I think I need to add some more logging in order to track this one down. If you aren't able to work around it I will push a version with more logging.

**Comment by Dhurcator** [comment] 2019-09-18 20:07
hi,

just to let you know that deleting the JSON files works! nice! thank you!

jceddy <notifications@github.com> escreveu no dia quarta, 18/09/2019 à(s)
14:48:

**Comment by jceddy** [comment] 2019-09-18 20:29
Good to hear it!
