### ISSUE TITLE
Unhandled Exception - Sending Data to Server

### ISSUE THREAD

**Issue by oysteinga** [jceddy/DailyArenaDeckAdvisor#109] opened 2019-12-03 12:31 UTC
After last update, the program hangs with the exception in the title.

Log files attached showing: FormatException (Number.ParseDouble)

[log2019120313.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3916551/log2019120313.txt)
[firstChanceExceptions2019120313.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3916558/firstChanceExceptions2019120313.txt)

**Comment by jceddy** [comment] 2019-12-03 15:24
Can you verify that it is still doing this for you? And if so, can you attach your Arena log here? (it's usually at c:\Users\\{Your User}\AppData\LocalLow\Wizards of the Coast\MTGA\output_log.txt)

The base exception is the same as reported automatically in issue #108, but after loading the Arena log that was attached to that issue, I am not able to reproduce it on my local machine.

**EDIT**: That was auto-reported for user Elric65#86556 ... if that is you, then I already have your log. It would also be useful if I could see your state.json file from C:\Users\\{Your User}\AppData\LocalLow\DailyArena\DailyArenaDeckAdvisor, as that can help me figure out if it only happens with specific filters applied.

**Comment by oysteinga** [comment] 2019-12-03 15:35
Still the same, and the auto-reported issue was not from me.

Arena log:
[output_log.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3917357/output_log.txt)

state.json :

{
  "LastFormat": "Standard",
  "LastSort": "Default",
  "LastSortDir": "Default",
  "RotationProof": false,
  "FontSize": 12,
  "Fingerprint": "931bc90d-65b3-4867-894b-2a780e84e12d",
  "Filters": {
    "HideFromCollection": false,
    "HideMissingWildcards": false,
    "HideMissingCards": false,
    "HideIncompleteReplacements": false,
    "HideScoreThreshold": false,
    "ScoreThreshold": 50,
    "HideGamesRecorded": false,
    "GamesThreshold": 1000,
    "HideMythic": false,
    "MythicCount": 0,
    "HideRare": false,
    "RareCount": 0,
    "HideUncommon": false,
    "UncommonCount": 0,
    "HideCommon": false,
    "CommonCount": 0
  },
  "CardTextFilter": ""
}

I also deleted the all the json-files to see if that helped, but it didn't, so the state.json is the new one, but the exception is still the same.

**Comment by jceddy** [comment] 2019-12-03 15:48
Hmm...after looking at this a bit longer, my suspicion is that there is some culture-dependent thing going on. Maybe double.Parse is getting a string that works in en-US (my culture), but not in yours.

(release 1.0.6.4 added a "minimum client version" check, which involved parsing the client version from the log...if your system culture doesn't treat something like "1968.747022" as a valid double, then it would throw an error).

Is there any chance you can attempt to look up your system culture for me?

One possibility is to navigate to http://www.localeplanet.com/support/browser.html and see what navigator.language is set to.

From the logs you sent me, it looks like Norwegian (this is a total guess...I don't speak it, but my wife does), so probably nb-NO or nn-NO, so I'll do some testing assuming those in the meantime.

**Comment by oysteinga** [comment] 2019-12-03 15:57
Norwegian is correct:
navigator.language: nb-NO

Some differences with English that I know of are:
- Decimal numbers often represented as , instead of .
- Three extra letters (Æ, Ø, Å) in the alphabet
- Date and time could also be different

But I don't know what that parse method is trying to parse or if it's possible to find that out more exactly.

**Comment by jceddy** [comment] 2019-12-03 16:01
I'm 80% sure that this is due to it trying to parse the client version (1968.747022) and throwing because Norwegian wants a comma instead of a dot. I'm going to do a little more testing to verify...if this is indeed the problem it should be an easy fix.

There was a version check added in the last version due to people having unhandled exceptions when running DADA against a log from an older incompatible version of the Arena client.

**Comment by jceddy** [comment] 2019-12-03 16:03
Alright, I've verified this one and have a fix (as well as adding a little code to log the culture so I don't have to ask for it if something like this crops up again). I'll push an update to the web as soon as I am able and ask you to test again. :)

**Comment by jceddy** [comment] 2019-12-03 17:32
Okay, I pushed version 1.0.6.6 ... can you check if that fixes your issue, when you have a chance?

**Comment by oysteinga** [comment] 2019-12-03 17:36
It works again on my end now. Thanks :)

**Comment by jceddy** [comment] 2019-12-03 17:37
Good to hear. Closing the issue.

**Closed as completed by jceddy** 2019-12-03 17:37 UTC
