### ISSUE TITLE
v1.0.3.3 not picking up all my cards in collection

### ISSUE THREAD

**Issue by ghost** [jceddy/DailyArenaDeckAdvisor#21] opened 2019-09-25 22:47 UTC
I noticed today that Budget Calamity is showing Experimental Frenzy as red and missing from my collection - however I have one Experimental Frenzy in my collection. I wonder if I don't have the total number for the deck if it is defaulting to a state where it thinks I don't have any.

![Screenshot_092519_064446_PM](https://user-images.githubusercontent.com/13244707/65645307-f647de80-dfc4-11e9-8245-e57235a6d29f.jpg)
![Screenshot_092519_064457_PM](https://user-images.githubusercontent.com/13244707/65645312-f811a200-dfc4-11e9-9210-6cdb28298c09.jpg)

**Comment by jceddy** [comment] 2019-09-25 22:56
It shows the collected ones and non-collected ones separately in a card-by-card basis. You can see that the copy you *do* own shows up in green a little further down the deck list.

Working as designed, so I'm closing the issue, but I appreciate the confusion. :)

**Comment by jceddy** [comment] 2019-09-25 22:57
Also note it is only suggesting replacements for 2 of the 3 from the deck, since you already own one.

**Closed as completed by jceddy** 2019-09-25 22:56 UTC

**Comment by ghost** [comment] 2019-09-25 23:00
derp - I did not see the one further down and thought was two in the deck -
I will review more closely going forward
